spring.application.name=TASTYCUISINE
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TASTYCUISINE;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=@ITB123456
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect